sudo: required

services:
  - docker

script:
  - docker-compose run --service-ports -e "API__URL=${API__URL}" -e "APP__URL=${APP__URL}" -e "NODE_ENV=${NODE_ENV}" app /bin/bash -c "cd /src && npm test"

after_success:
  - |
      if [[ ($TRAVIS_BRANCH == master) &&
            ($TRAVIS_PULL_REQUEST == false) &&
            ( (! $TRAVIS_JOB_NUMBER == *.*) || ($TRAVIS_JOB_NUMBER == *.1) ) ]] ; then
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        docker tag haardashboard_app stuartalexwhitehead/haar-dashboard:latest
        docker push stuartalexwhitehead/haar-dashboard:latest
      fi
