app:
  container_name: haar-dashboard_app
  build: .
  ports:
    - "3001:3001"
  volumes:
    - .:/src
    - /src/node_modules # http://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds